<?php

use App\Models\Country;

return [
    ["label" => " Safra National Bank of New York", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Santander Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Saratoga National Bank and Trust Company", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Savannah Bank National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Schaumburg Bank & Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Seacoast National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Securian Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Security First National Bank of Hugo", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Security National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Security National Bank of Omaha", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Security National Bank of South Dakota", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Security National Trust Co", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Shamrock Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Signature Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Skyline National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " SNB Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Solera National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " South State Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " SouthCrest Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Southeast First National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Southtrust Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Southwest National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Southwestern National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " St Martin National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " St Martin National Bank Martin National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " State Bank of the Lakes, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " State Street Bank and Trust Company National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " State Street Bank and Trust Company of California, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stearns Bank Holdingford National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stearns Bank National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stearns Bank Upsala National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Sterling National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stifel Trust Company Delaware, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stifel Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stillman Banccorp National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stockmens National Bank in Cotulla", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stride Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Stroud National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Summit National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Sunflower Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Sunrise Banks, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Superior National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Synovus Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " T Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TCF National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TCM Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TD Bank USA, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TD Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Terrabank National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texan Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texana Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Advantage Community Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Capital Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Citizens Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Gulf Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Heritage National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas National Bank of Jacksonville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Texas Republic Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TexStar National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The American National Bank of Mount Pleasant", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The American National Bank of Texas", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Atlanta National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Bank National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Bank of New York Mellon Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Bradford National Bank of Greenville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Brady National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Brenham National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Camden National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Canandaigua National Bank and Trust Company", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Central National Bank of Poteau", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Chicago Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens First National Bank of Storm Lake", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Bluffton", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Hammond", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Hillsboro", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Lebanon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of McConnelsville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Meridian", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Park Rapids", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Quitman", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Somerset", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Citizens National Bank of Woodsfield", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank and Trust Company of Lawton, Oklahoma", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank of Colorado City", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank of Metropolis", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank of San Saba", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank of Sulphur Springs", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The City National Bank of Taylor", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Clinton National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Commercial National Bank of Brady", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Conway National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Delaware National Bank of Delhi", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Ephrata National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Fairfield National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Falls City National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers and Merchants National Bank of Fairview", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers and Merchants National Bank of Nashville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers' National Bank of Canfield", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers National Bank of Danville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers National Bank of Emlenton", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Farmers National Bank of Lebanon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Fayette County National Bank of Fayetteville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First Central National Bank of St Paris", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First Citizens National Bank of Upper Sandusky", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First Farmers National Bank of Waurika", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First Liberty National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank & Trust Co of Iron Mountain", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Co", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company of Broken Arrow", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company of Miami", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company of Newtown", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company of Okmulgee", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank and Trust Company of Vinita", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank at Paris", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank at St James", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Amboy", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Carlyle", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Cooper", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Creston", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Falfurrias", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Marlow", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Sioux Falls", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Tremont", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank in Trinidad", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Absecon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Allendale", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Anson", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Arenzville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Aspermont", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Assumption", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Ava", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Ballinger", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Bangor", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Bastrop", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Bellevue", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Bellville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Bemidji", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Blanchester", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Brooksville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Brownstown", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Buhl", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Carmi", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Cokato", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Coleraine", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Dennison", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Dighton", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Dozier", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Dryden", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Eagle Lake", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of East Texas", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Eldorado", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Elmer", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Ely", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Evant", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Fairfax", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Fleming", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Fletcher", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Floydada", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Fort Smith", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Frederick", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Germantown", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Gilbert", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Gordon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Granbury", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Grayson", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Groton", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hartford", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Harveyville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hebbronville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Henning", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hooker", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hope", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hughes Springs", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hugo", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Hutchinson", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Izard County", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Jeanerette", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Johnson", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Kemp", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Lacon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Lawrence County at Walnut Ridge", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Le Center", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Lindsay", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Lipan", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Litchfield", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Livingston", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Long Island", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Louisburg", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Manchester", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Manning", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of McConnelsville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of McIntosh", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Mertzon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Middle Tennessee", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Milaca", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Monterey", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Moody", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Moose Lake", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Mount Dora", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Nevada, Missouri", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Okawville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Oneida", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Orwell", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Osakis", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Ottawa", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Pandora", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Peterstown", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Primghar", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Proctor", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Quitaque", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Raymond", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Russell Springs", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sandoval", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Scott City", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sedan", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Shiner", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sonora", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of South Miami", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sparta", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Spearville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of St Ignace", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Stanton", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sterling City", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Stigler", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Sycamore", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Syracuse", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Tahoka", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Tom Bean", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Trinity", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Wakefield", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Waseca", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Waterloo", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Waverly", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Waynesboro", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Weatherford", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First National Bank of Williamson", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The First, A National Banking Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Fisher National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Glenmede Trust Company, National", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Goldman Sachs Trust Company, National", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Granger National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Granville National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Havana National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Home National Bank of Thorntown", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Hondo National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Honesdale National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Huntington National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Idabel National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Jacksboro National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Karnes County National Bank of Karnes City", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Lamesa National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Lemont National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Liberty National Bank in Paris", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Lincoln National Bank of Hodgenville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Litchfield National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Lyons National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Malvern National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Marion National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Merchants National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Miners National Bank of Eveleth", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Mint National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Adams County of West Union", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Andrews", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Blacksburg", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Coxsackie", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Indianapolis", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Malvern", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Middlebury", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Bank of Texas at Fort Worth", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Capital Bank of Washington", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Grand Bank of Marblehead", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The National Iron Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Neffs National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Northumberland National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Old Exchange National Bank of Okawville", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Old Point National Bank of Phoebus", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Park National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Pauls Valley National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Pennsville National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Peoples National Bank of Checotah", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Perryton National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Peshtigo National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Private Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Putnam County National Bank of Carmel", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Riddell National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Salyersville National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Santa Anna National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Security National Bank of Enid", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Security National Bank of Sioux City, Iowa", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The State National Bank of Big Spring", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The State National Bank of Groom", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Stephenson National Bank and Trust", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Tipton Latham Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Trust Company of Toledo, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Turbotville National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The University National Bank of Lawrence", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Upstate National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Vinton County National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Waggoner National Bank of Vernon", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " The Yoakum National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Thomasville National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " TIB The Independent Bankers Bank, National", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Tioga State Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Titan Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Touchmark National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Town Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Town-Country National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Transact Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Tri City National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Triad Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Trinity Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Trustmark National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " UMB Bank & Trust, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " UMB Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Union National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " United Bank & Trust National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " United Midwest Savings Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " United National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => " Unity National Bank of Houston", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "1st National Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Abacus Federal Savings Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Abbeville Building & Loan", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Abbeville First Bank, SSB", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "AbbyBank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Abington Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Academy Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Academy Bank, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "ACB Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Access Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "AccessBank Texas", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "ACNB Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Adams Bank & Trust", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Adams Community Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Adams County Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Adams State Bank", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "ADP Trust Company", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "US Bank National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "US Bank Trust Company, National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "US Bank Trust National Association", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "US Bank Trust National Association SD", "country_id" => Country::where("code", "USA")->first()?->id],
    ["label" => "Bank Saderat Tashkent", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial  Aloqabank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial  Mikrokreditbank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial  Turon Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Agrobank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Asia Alliance Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Invest Finance Bank  with foreign capital", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Kapitalbank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Qishloq Qurilish Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  TBC Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Tenge Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank  Uzpromstroybank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank with foreign capital  HamkorBank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Bank with foreign capital  Savdogar ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial Mortgage Bank  Ipoteka Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  Anor Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  Asakabank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  KDB Bank Uzbekistan ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  Poytaxt Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  Ravnaq-Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Company  Ziraat Bank Uzbekistan ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Innovation Commercial Bank  Ipak Yuli ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Joint-Stock Commercial People’s Bank of the Republic of Uzbekistan", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Closed Joint-Stock Commercial Bank  Hi-Tech Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Closed Joint-Stock Commercial Bank  Orient Finans ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Joint-Stock Bank  Trustbank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Joint-Stock Commercial  Madad Invest Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Joint-Stock Commercial Bank  Davr Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Joint-Stock Commercial Bank  Turkistan ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "Private Joint-Stock Commercial Bank  Universal Bank ", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "The National Bank for Foreign Economic Activity of the Republic of Uzbekistan", "country_id" => Country::where("code", "UZB")->first()?->id],
    ["label" => "An Binh Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Asia Commercial Bank (ACB)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Bac A Commercial Joint Stock Bank (Bac A Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Bangkok Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Bank of China", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Bank of India", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Bao Viet Joint Stock Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "BNP Paribas", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "CIMB Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Commonwealth Bank of Australia", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Deutsche Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Gatehouse Bank of United Kingdom", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Global Petro Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Great Asia Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Great Trust Joint Stock Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Hanoi Building Joint-stock Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "HFC Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Hong Leong Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Housing development Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "HSBC", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Industrial Bank of Korea", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "JP Morgan Chase Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "KEB Hana Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Kien Long Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "LienViet Post Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Maritime Commercial Joint Stock Bank (Maritime Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Maybank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Mekong Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Mekong Development Joint Stock Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Military Commercial Joint Stock Bank (MB Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Mizuho Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Nam Viet Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Natixis", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "OCEAN Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Orient Commercial Joint Stock Bank (OCB)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Petrolimex Group Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Public Bank Vietnam", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Sai Gon Joint Stock Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Sai Gon Thuong Tin Commercial Joint-stock Bank (Sacombank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Saigon-Hanoi Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Scotiabank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Shinhan Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Siam Commercial Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Southeast Asia Commercial Joint Stock Bank (SeABank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Southern Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Standard Chartered Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "The Bank of Tokyo-Mitsubishi UFJ", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Tien Phong Commercial Joint Stock Bank (TP Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "United Overseas Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Viet A Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Viet Capital Commercial Joint Stock Bank (Viet Capital Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Viet Nam Public Bank (PVcomBank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Viet Nam Technological and Commercial Joint Stock Bank (Techcombank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Viet Nam thuong Tin Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Vietnam International Commercial Joint Stock Bank (VIB)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Vietnam Prosperity Joint Stock Commercial Bank (VPBank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Western Bank (Phuong Tay Bank)", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Western Rural Commercial Joint Stock Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Woori Bank", "country_id" => Country::where("code", "VNM")->first()?->id],
    ["label" => "Access Bank Zambia", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "BancABC", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Bank of China", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Barclays Banknow Absa Zambia", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Cavmont Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Citibank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Ecobank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Finance Bank Zambia Limited", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "FINCA International", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "First Alliance Bank Zambia Limited", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "First National Bank (South Africa)", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Indo-Zambia Bank Limited", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "International Commercial Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Investrust Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Stanbic Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Standard Chartered Bank (Zambia)", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "United Bank for Africa", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Zambia Industrial Commercial Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "Zambia National Commercial Bank", "country_id" => Country::where("code", "ZMB")->first()?->id],
    ["label" => "African Century Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "African Development Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Agri Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "BancABC", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Barclays Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "CBZ Bank Limited", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "CFX Bank, formerly CFX Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Ecobank Zimbabwe", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "FBC Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "First Merchant Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Genesis Investment Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Metropolitan Bank of Zimbabwe", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "NBS Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "NED Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "NMB Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Peoples Own Savings Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Stanbic Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Standard Chartered Bank (Zimbabwe)", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Steward Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Trust Merchant Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Universal Merchant Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
    ["label" => "Zb Bank", "country_id" => Country::where("code", "ZWE")->first()?->id],
];
